### ISSUE TITLE
Error when using Github Actions and building with Docker 23

### ISSUE THREAD

**Issue by tobiasc** [macbre/push-to-ghcr#29]
We encountered a build error when running Github Actions and building the Dockerfile with Docker 23.0.6, whereas it worked on Docker 20.10.25. 
The error message read: `ERROR: failed to get console: provided file is not a console`

We didn't upgrade on purpose, as I'm not even sure where the Docker config is located, so this probably happened due to some other upgrade or rebuilt of upstream dependencies.

I wasn't able to find much/anything on this error specifically, but the Docker build flag TTY was mentioned in a few Stack Overflow posts that seemed vaguely related, eg. https://stackoverflow.com/questions/70855915/fix-panic-provided-file-is-not-a-console-from-docker-compose-in-github-action

I noticed that the TTY flag was used in this line: https://github.com/macbre/push-to-ghcr/blob/master/action.yml#L93

I forked the repo and tried removing that line and it worked. https://github.com/macbre/push-to-ghcr/compare/master...tobiasc:push-to-ghcr:master

**Working (Docker 20)**
![Docker_20](https://github.com/macbre/push-to-ghcr/assets/698574/aa230fed-50a1-4477-addf-2d9c52a15311)

**Broken (Docker 23 + original repo)**
![Docker_23](https://github.com/macbre/push-to-ghcr/assets/698574/e89ea1ab-da2e-43ee-a784-65db5b6fc4df)

**Fixed (Docker 23 + forked with fix repo)**
![Docker_23_fixed](https://github.com/macbre/push-to-ghcr/assets/698574/5af908af-3b3c-4df0-840a-e31364a88dab)

**Comment by macbre** [comment]
Thanks, @tobiasc for the bug report and the screenshots!

**Comment by macbre** [comment]
Resolved by #30

**Comment by thomaspaulin** [comment]
I'm still seeing this today using `master`.

```
  docker_publish:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          image_tag: $(date +%s)
          github_token: ${{ secrets.GITHUB_TOKEN }}
 ```

![push-to-ghcr-fail](https://github.com/macbre/push-to-ghcr/assets/7918983/5a60bc57-1259-4f06-a2bc-b3a4f2188652)
